# Lightweight Dockerfile using existing packaged jar
FROM eclipse-temurin:25-jre
WORKDIR /app
COPY target/circuit-breaker-pattern-0.0.1-SNAPSHOT.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
